// Code generated by "stringer -type MessageType"; DO NOT EDIT.

package notifier

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Notification-1]
	_ = x[Failure-2]
	_ = x[OK-3]
	_ = x[Aggregate-4]
}

const _MessageType_name = "UndefinedNotificationFailureOKAggregate"

var _MessageType_index = [...]uint8{0, 9, 21, 28, 30, 39}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
