// Code generated by "stringer -type EventType -linecomment"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUndefined-0]
	_ = x[TypeInfo-1]
	_ = x[TypeFailure-2]
}

const _EventType_name = "UndefinedInfoFailure"

var _EventType_index = [...]uint8{0, 9, 13, 20}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
