// Code generated by "stringer -type State -linecomment"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUndefined-0]
	_ = x[StateHealthy-1]
	_ = x[StateUnhealthy-2]
}

const _State_name = "UndefinedHealthyUnhealthy"

var _State_index = [...]uint8{0, 9, 16, 25}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
